const dotenv = require('dotenv');

export const config = {
  PORT: process.env.PORT,
  DB_URL: process.env.DB_URL,
  JWT_TOKEN_SECRET: process.env.JWT_TOKEN_SECRET,
  REFRESH_JWT_TOKEN_SECREAT: process.env.REFRESH_JWT_TOKEN_SECREAT,
  AWS_KEY_ID: process.env.AWS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  REGION: process.env.REGION,
  BUCKET_NAME: process.env.BUCKET_NAME,
  BUCKET_URL: process.env.BUCKET_URL,
  MAIL: process.env.MAIL,
  MAIL_PASSWORD: process.env.MAIL_PASSWORD,
  SERVICE: process.env.SERVICE,
  FCM_KEY: process.env.FCM_KEY,
  BACKEND_URL: process.env.BACKEND_URL,
  ENV: process.env.ENV,
  TWIlIO_ACCOUNT_ID: process.env.TWIlIO_ACCOUNT_ID,
  TWIlIO_AUTH_TOKEN: process.env.TWIlIO_AUTH_TOKEN,
  TWIlIO_PHONE_NUMBER: process.env.TWIlIO_PHONE_NUMBER,
  GMAIL_ACCESS_TOKEN: process.env.GMAIL_ACCESS_TOKEN,
  GMAIL_REFRESH_TOKEN: process.env.GMAIL_REFRESH_TOKEN,
  GMAIL_CLIENT_ID: process.env.GMAIL_CLIENT_ID,
  GMAIL_CLIENT_SECRET: process.env.GMAIL_CLIENT_SECRET,
  GMAIL_PASSWORD: process.env.GMAIL_PASSWORD,
}